FROM registry.redhat.io/ubi9/go-toolset:latest AS builder
USER root

WORKDIR /workspace

# Copy the go source
COPY ./coredns/*.go ./
COPY ./coredns/go.mod go.mod
COPY ./coredns/go.sum go.sum
COPY ./coredns/core/ core/
COPY ./coredns/coremain/ coremain/
COPY ./coredns/plugin/ plugin/
COPY ./coredns/request/ request/
COPY ./coredns/pb/ pb/
COPY coredns/LICENSE /licenses/LICENSE

# Build CoreDNS with the Kuadrant plugin
RUN GO111MODULE=on go build -o coredns .
USER 1001

FROM registry.redhat.io/ubi9/ubi-minimal:latest
USER 1001
COPY --from=builder /workspace/coredns /usr/bin/coredns
COPY --from=builder licenses/LICENSE /licenses/LICENSE
USER nonroot:nonroot
EXPOSE 53 53/udp


ENTRYPOINT ["/usr/bin/coredns"]

LABEL version="1.2.0" \
      summary="Red Hat CoreDNS Container Image" \
      description="Red Hat CoreDNS is a DNS server that chains plugins" \
      name="coredns" \
      com.redhat.component="Red Hat CoreDNS" \
      io.k8s.display-name="Red Hat CoreDNS" \
      io.k8s.description="CoreDNS is a fast and flexible DNS server" \
      io.openshift.tags="dns,coredns" \
      io.openshift.expose-services="" \
      vendor="Red Hat, Inc."
