FROM registry.redhat.io/ubi9/go-toolset:latest AS builder
WORKDIR /workspace
COPY coredns/ .
RUN GO111MODULE=on GOFLAGS=-mod=vendor go build -o coredns .

FROM registry.redhat.io/ubi9/ubi-minimal:latest
COPY --from=builder /workspace/coredns /usr/bin/coredns

ENTRYPOINT ["/usr/bin/coredns"]

LABEL version="1.2.0" \
      summary="Red Hat CoreDNS Container Image" \
      description="Red Hat CoreDNS is a DNS server that chains plugins" \
      name="coredns" \
      com.redhat.component="Red Hat CoreDNS" \
      io.k8s.display-name="Red Hat CoreDNS" \
      io.k8s.description="CoreDNS is a fast and flexible DNS server" \
      io.openshift.tags="dns,coredns" \
      io.openshift.expose-services="" \
      vendor="Red Hat, Inc."
