FROM registry.redhat.io/ubi9/go-toolset:latest AS builder
USER root

ARG GIT_SHA=unknown
ARG PLUGIN_VERSION=unknown

WORKDIR /workspace

# Copy the go source from dns-operator/coredns/plugin
COPY ./dns-operator/coredns/plugin/go.mod go.mod
COPY ./dns-operator/coredns/plugin/go.sum go.sum
COPY ./dns-operator/coredns/plugin/*.go ./
COPY ./dns-operator/coredns/plugin/cmd/ cmd/
COPY ./dns-operator/coredns/plugin/dnsop/ dnsop/
COPY ./dns-operator/coredns/plugin/geoip/ geoip/
COPY ./dns-operator/LICENSE /licenses/LICENSE

# Build CoreDNS with the Kuadrant plugin
# Note: main package is in cmd/ subdirectory
RUN CGO_ENABLED=0 GO111MODULE=on go build -ldflags "-X main.pluginVersion=${PLUGIN_VERSION} -X main.gitSHA=${GIT_SHA}" -o coredns ./cmd/
USER 1001

FROM registry.redhat.io/ubi9/ubi-minimal:latest AS build
USER root
# Based on https://github.com/coredns/coredns/blob/master/Dockerfile
# Requires this stage to avoid "Listen tcp :53: bind: permission denied" errors in nonroot containers.
SHELL [ "/bin/sh", "-ec" ]
COPY --from=builder /workspace/coredns /coredns
RUN setcap cap_net_bind_service=+ep /coredns
USER 1001

FROM registry.redhat.io/ubi9/ubi-minimal:latest
USER 1001
COPY --from=build /coredns /coredns
COPY --from=builder /licenses/LICENSE /licenses/LICENSE
EXPOSE 53 53/udp

ENTRYPOINT ["/coredns"]

ARG PLUGIN_VERSION=unknown
LABEL version="${PLUGIN_VERSION}" \
      summary="Red Hat CoreDNS Container Image" \
      description="Red Hat CoreDNS is a DNS server that chains plugins" \
      name="rhcl-1/coredns-rhel9" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      com.redhat.component="Red Hat CoreDNS" \
      io.k8s.display-name="Red Hat CoreDNS" \
      io.k8s.description="CoreDNS is a fast and flexible DNS server" \
      io.openshift.tags="dns,coredns" \
      io.openshift.expose-services="" \
      vendor="Red Hat, Inc."
